# Generated by Django 4.2.3 on 2023-09-06 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('set_blocked', 'Can blocked')]},
        ),
    ]
