# Generated by Django 4.2.3 on 2023-09-02 11:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0002_alter_client_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['time'], 'verbose_name': 'settings', 'verbose_name_plural': 'settings'},
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='time'),
        ),
    ]
