# Generated by Django 4.2.3 on 2023-09-06 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['time'], 'permissions': [('set_disabled', 'Can disabled')], 'verbose_name': 'newsletter', 'verbose_name_plural': 'newsletters'},
        ),
    ]
