# Generated by Django 4.2.3 on 2023-09-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0003_alter_newsletter_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
